name: workspace publish

on:
  push:
    branches: [main, workspace_publish]

env:
  DENO_UNSTABLE_WORKSPACES: true

jobs:
  publish:
    runs-on: ubuntu-22.04
    timeout-minutes: 30

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 19d52b9a55a6d5a67f27cbcc6cbe9c6c15865d63

      - name: Convert to workspace
        run: deno run -A ./_tools/convert_to_workspace.ts

      - name: Format
        run: deno fmt

      - name: Type check
        run: deno test --unstable --no-run --doc

      - name: Publish (workspace publish or tag push)
        if: github.ref == 'refs/heads/workspace_publish' || startsWith(github.ref, 'refs/tags/')
        run: deno do-not-use-publish .
        env:
          DENO_REGISTRY_URL: https://${{ secrets.DENO_REGISTRY_BASE }}
          DENO_REGISTRY_API_URL: https://api.${{ secrets.DENO_REGISTRY_BASE }}
